env:
  TERM: xterm-256color

window:
  # dimensions:
  # columns: 165
  # lines: 48

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  # x: 550
  # y: 120

  # Window padding (changes require restart)
  padding:
    x: 10
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background and no title bar buttons
  decorations: buttonless

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 1

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  # - SimpleFullscreen
  startup_mode: Maximized

  # Window title
  #title: Alacritty

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: FiraCode Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraCode Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraCode Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraCode Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 14

  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  offset:
    # x: 10
    y: 6

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  # glyph_offset:
  #  x: 0
  #  y: 0

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`.
  AppleFontSmoothing: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors
colors:
  primary:
    background: '#282C34'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'

  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'

    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'

    footer_bar:
      background: '#282a36'
      foreground: '#f8f8f2'

  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'

    end:
      foreground: '#f1fa8c'
      background: '#282a36'

  line_indicator:
    foreground: None
    background: None

  selection:
    text: CellForeground
    background: '#44475a'

  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#04bfff'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'

  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#04cfff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'

cursor:
  style:
    shape: Block
    blinking: Always

live_config_reload: true

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - 'tmux attach || tmux'
    - --login
